version: '2'
services:
  redis:
    image: sameersbn/redis:latest
    volumes:
      - /srv/docker/gitlab/redis:/var/lib/redis

  postgresql:
    image: sameersbn/postgresql:9.6-2
    volumes:
      - /srv/docker/gitlab/postgresql:/var/lib/postgresql
    environment:
      - DB_NAME=gitlabhq_production
      - DB_USER=gitlab
      - DB_PASS=password

  gitlab:
    image: sameersbn/gitlab:9.0.5
    volumes:
      - /srv/docker/gitlab/gitlab:/home/git/data
    depends_on:
      - postgresql
      - redis
    ports:
      - "10022:22"
      - "10080:80"
    environment:
      - GITLAB_PORT=10080
      - GITLAB_SSH_PORT=10022

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=redis
      - REDIS_PORT=6379
